[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "decryptoai"
version = "0.0.1"
authors = [
  { name="Jaden Rodriguez", email="jadenrodriguez7@gmail.com" },
]